// 1. The Base interface (Corresponds to your full record in the DB)
export interface AttributeInDb {
  id: number;
  users_id: number;
  name: string;
  description?: string | null;
  icon?: Buffer | null;
  level?: number | null;
  xp?: number | null;
  xp_to_next_level: number;
  decay_date?: Date | null;
}

// 2. Creation (NewAttribute)
// We remove id, stats, and decay_date since they are generated by the DB or calculated later.
export type NewAttribute = Omit<
  AttributeInDb,
  "id" | "level" | "xp" | "xp_to_next_level" | "decay_date"
>;

// 3. Update (UpdatedAttribute)
// We make properties optional and omit immutable properties like id and users_id.
export type UpdatedAttribute = Partial<Omit<AttributeInDb, "id" | "users_id">>;

// An object of type Attribute can be a complete DB record, an update payload, or a new creation payload.
export type Attribute = AttributeInDb | UpdatedAttribute | NewAttribute;

export type AttributesLvlsPerUser = {
  userId: number;
  attributeLevels: number[];
};
