// 1. The Base interface (Corresponds to your full record in the DB)
export interface QuestInDb {
  id: number;
  users_id: number;
  name: string;
  description?: string | null;
  icon?: Buffer | null; // bytea -> Buffer
  total_xp?: number | null; // calculated, may be missing or NULL
  is_rewardable: boolean;
  is_tracked: boolean;
  tracked_at?: Date | null; // timestamp, but initially NULL
  is_completed: boolean;
  completed_at?: Date | null; // NULL until completed
  estimated_time?: number | null; // integer minutes, can be NULL if not rewardable
  actual_time?: number | null; // integer minutes, NULL until complete
}

// 2. Creation (NewQuest)
// We remove the id, since it is usually automatically generated by the Database.
export type NewQuest = Omit<QuestInDb, "id">;

// 3. Update (UpdatedQuest)
// We use Partial to make all properties optional.
// We use Omit to prevent id and users_id from updating (usually immutable).
export type UpdatedQuest = Partial<Omit<QuestInDb, "id" | "users_id">>;

// An object of type Quest can be a complete Quest,
// a new Quest without ID, or a partial update object.
export type Quest = QuestInDb | UpdatedQuest | NewQuest;
